version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/team36db"
    depends_on:
      db:
        condition: service_healthy  # app waits for db to be healthy
    restart: no                     # No restart if app fails
    healthcheck:                    # Healthcheck for the app container
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["npm", "run", "dev:init"]

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: team36db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no                     # No restart if database fails
    healthcheck:                    # Healthcheck for the database
      test: ["CMD-SHELL", "pg_isready -U admin -d team36db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: {}